QT       += core gui 3dcore 3drender 3dinput 3dlogic 3dextras 3danimation

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

QMAKE_CXXFLAGS += -fopenmp

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0
LIBS += -fopenmp


SOURCES += \
    SurfaceReconstruction/alg/kernel/cubic_spline_kernel.cpp \
    SurfaceReconstruction/alg/kernel/spiky_kernel.cpp \
    SurfaceReconstruction/alg/level/dimensionless_level_set_function.cpp \
    SurfaceReconstruction/alg/marching_cubes_reconstructor.cpp \
    SurfaceReconstruction/alg/nsearch/spatial_hashing_neighborhood_search.cpp \
    SurfaceReconstruction/alg/post/open_mesh_processor.cpp \
    SurfaceReconstruction/data/graph.cpp \
    SurfaceReconstruction/data/particle.cpp \
    SurfaceReconstruction/data/particle_list.cpp \
    SurfaceReconstruction/data/triangle_list.cpp \
    SurfaceReconstruction/in/partio_particle_reader.cpp \
    SurfaceReconstruction/in/ply_triangle_reader.cpp \
    SurfaceReconstruction/in/vtk_particle_reader.cpp \
    SurfaceReconstruction/in/vtk_triangle_reader.cpp \
    SurfaceReconstruction/out/ply_triangle_writer.cpp \
    SurfaceReconstruction/out/vtk_triangle_writer.cpp \
    CompactNSearch/src/CompactNSearch.cpp \
    OpenMesh/Core/IO/BinaryHelper.cc \
    OpenMesh/Core/IO/IOManager.cc \
    OpenMesh/Core/IO/OMFormat.cc \
    OpenMesh/Core/IO/reader/BaseReader.cc \
    OpenMesh/Core/IO/reader/OBJReader.cc \
    OpenMesh/Core/IO/reader/OFFReader.cc \
    OpenMesh/Core/IO/reader/OMReader.cc \
    OpenMesh/Core/IO/reader/PLYReader.cc \
    OpenMesh/Core/IO/reader/STLReader.cc \
    OpenMesh/Core/IO/writer/BaseWriter.cc \
    OpenMesh/Core/IO/writer/OBJWriter.cc \
    OpenMesh/Core/IO/writer/OFFWriter.cc \
    OpenMesh/Core/IO/writer/OMWriter.cc \
    OpenMesh/Core/IO/writer/PLYWriter.cc \
    OpenMesh/Core/IO/writer/STLWriter.cc \
    OpenMesh/Core/IO/writer/VTKWriter.cc \
    OpenMesh/Core/Mesh/ArrayKernel.cc \
    OpenMesh/Core/Mesh/BaseKernel.cc \
    OpenMesh/Core/Mesh/PolyConnectivity.cc \
    OpenMesh/Core/Mesh/SmartHandles.cc \
    OpenMesh/Core/Mesh/TriConnectivity.cc \
    OpenMesh/Core/System/omstream.cc \
    OpenMesh/Core/Utils/BaseProperty.cc \
    OpenMesh/Core/Utils/Endian.cc \
    OpenMesh/Core/Utils/RandomNumberGenerator.cc \
    OpenMesh/Tools/Decimater/Observer.cc \
    OpenMesh/Tools/Utils/Gnuplot.cc \
    OpenMesh/Tools/Utils/Timer.cc \
    OpenMesh/Tools/Utils/conio.cc \
    OpenMesh/Tools/Utils/getopt.c \
    OpenMesh/Tools/VDPM/VFront.cc \
    OpenMesh/Tools/VDPM/VHierarchy.cc \
    OpenMesh/Tools/VDPM/VHierarchyNodeIndex.cc \
    OpenMesh/Tools/VDPM/VHierarchyWindow.cc \
    OpenMesh/Tools/VDPM/ViewingParameters.cc \
    main.cpp \
    mainwindow.cpp \
    surfrec_io/code/io.cpp \
    surfrec_io/extern/partio/src/lib/core/Particle.cpp \
    surfrec_io/extern/partio/src/lib/core/ParticleCaching.cpp \
    surfrec_io/extern/partio/src/lib/core/ParticleHeaders.cpp \
    surfrec_io/extern/partio/src/lib/core/ParticleSimple.cpp \
    surfrec_io/extern/partio/src/lib/core/ParticleSimpleInterleave.cpp \
    surfrec_io/extern/partio/src/lib/io/BGEO.cpp \
    surfrec_io/extern/partio/src/lib/io/BIN.cpp \
    surfrec_io/extern/partio/src/lib/io/GEO.cpp \
    surfrec_io/extern/partio/src/lib/io/MC.cpp \
    surfrec_io/extern/partio/src/lib/io/PDA.cpp \
    surfrec_io/extern/partio/src/lib/io/PDB.cpp \
    surfrec_io/extern/partio/src/lib/io/PDC.cpp \
    surfrec_io/extern/partio/src/lib/io/PRT.cpp \
    surfrec_io/extern/partio/src/lib/io/PTC.cpp \
    surfrec_io/extern/partio/src/lib/io/PTS.cpp \
    surfrec_io/extern/partio/src/lib/io/ParticleIO.cpp \
    surfrec_io/extern/partio/src/lib/io/RIB.cpp \
    surfrec_io/extern/partio/src/lib/io/ZIP.cpp \
    surfrec_io/extern/zlib/src/adler32.c \
    surfrec_io/extern/zlib/src/compress.c \
    surfrec_io/extern/zlib/src/crc32.c \
    surfrec_io/extern/zlib/src/deflate.c \
    surfrec_io/extern/zlib/src/gzio.c \
    surfrec_io/extern/zlib/src/infback.c \
    surfrec_io/extern/zlib/src/inffast.c \
    surfrec_io/extern/zlib/src/inflate.c \
    surfrec_io/extern/zlib/src/inftrees.c \
    surfrec_io/extern/zlib/src/trees.c \
    surfrec_io/extern/zlib/src/uncompr.c \
    surfrec_io/extern/zlib/src/zutil.c

HEADERS += \
    SurfaceReconstruction/alg/kernel/SPH_interpolation_kernel.h \
    SurfaceReconstruction/alg/kernel/cubic_spline_kernel.h \
    SurfaceReconstruction/alg/kernel/spiky_kernel.h \
    SurfaceReconstruction/alg/level/dimensionless_level_set_function.h \
    SurfaceReconstruction/alg/level/level_set_function.h \
    SurfaceReconstruction/alg/marching_cubes_reconstructor.h \
    SurfaceReconstruction/alg/nsearch/compact_neighborhood_search.h \
    SurfaceReconstruction/alg/nsearch/spatial_hashing_neighborhood_search.h \
    SurfaceReconstruction/alg/post/open_mesh_processor.h \
    SurfaceReconstruction/alg/post/post_processor.h \
    SurfaceReconstruction/alg/surface_reconstructor.h \
    SurfaceReconstruction/data/graph.h \
    SurfaceReconstruction/data/particle.h \
    SurfaceReconstruction/data/particle_list.h \
    SurfaceReconstruction/data/triangle_list.h \
    SurfaceReconstruction/in/particle_reader.h \
    SurfaceReconstruction/in/partio_particle_reader.h \
    SurfaceReconstruction/in/ply_triangle_reader.h \
    SurfaceReconstruction/in/reader.h \
    SurfaceReconstruction/in/triangle_reader.h \
    SurfaceReconstruction/in/vtk_particle_reader.h \
    SurfaceReconstruction/in/vtk_triangle_reader.h \
    SurfaceReconstruction/out/ply_triangle_writer.h \
    SurfaceReconstruction/out/triangle_writer.h \
    SurfaceReconstruction/out/vtk_triangle_writer.h \
    SurfaceReconstruction/out/writer.h \
    CompactNSearch/extern/libmorton/libmorton/include/morton.h \
    CompactNSearch/extern/libmorton/libmorton/include/morton2D.h \
    CompactNSearch/extern/libmorton/libmorton/include/morton2D_LUTs.h \
    CompactNSearch/extern/libmorton/libmorton/include/morton3D.h \
    CompactNSearch/extern/libmorton/libmorton/include/morton3D_LUTs.h \
    CompactNSearch/extern/libmorton/libmorton/include/morton_BMI.h \
    CompactNSearch/extern/libmorton/libmorton/include/morton_LUT_generators.h \
    CompactNSearch/extern/libmorton/libmorton/include/morton_common.h \
    CompactNSearch/include/CompactNSearch \
    CompactNSearch/include/CompactNSearch.h \
    CompactNSearch/include/Config.h \
    CompactNSearch/include/DataStructures.h \
    CompactNSearch/include/PointSet.h \
    OpenMesh/Core/Geometry/Config.hh \
    OpenMesh/Core/Geometry/EigenVectorT.hh \
    OpenMesh/Core/Geometry/LoopSchemeMaskT.hh \
    OpenMesh/Core/Geometry/MathDefs.hh \
    OpenMesh/Core/Geometry/NormalConeT.hh \
    OpenMesh/Core/Geometry/NormalConeT_impl.hh \
    OpenMesh/Core/Geometry/Plane3d.hh \
    OpenMesh/Core/Geometry/QuadricT.hh \
    OpenMesh/Core/Geometry/Vector11T.hh \
    OpenMesh/Core/Geometry/VectorT.hh \
    OpenMesh/Core/Geometry/VectorT_inc.hh \
    OpenMesh/Core/IO/BinaryHelper.hh \
    OpenMesh/Core/IO/IOInstances.hh \
    OpenMesh/Core/IO/IOManager.hh \
    OpenMesh/Core/IO/MeshIO.hh \
    OpenMesh/Core/IO/OFFFormat.hh \
    OpenMesh/Core/IO/OMFormat.hh \
    OpenMesh/Core/IO/OMFormatT_impl.hh \
    OpenMesh/Core/IO/Options.hh \
    OpenMesh/Core/IO/SR_binary.hh \
    OpenMesh/Core/IO/SR_binary_spec.hh \
    OpenMesh/Core/IO/SR_binary_vector_of_bool.inl \
    OpenMesh/Core/IO/SR_binary_vector_of_fundamentals.inl \
    OpenMesh/Core/IO/SR_binary_vector_of_string.inl \
    OpenMesh/Core/IO/SR_rbo.hh \
    OpenMesh/Core/IO/SR_store.hh \
    OpenMesh/Core/IO/SR_types.hh \
    OpenMesh/Core/IO/StoreRestore.hh \
    OpenMesh/Core/IO/exporter/BaseExporter.hh \
    OpenMesh/Core/IO/exporter/ExporterT.hh \
    OpenMesh/Core/IO/importer/BaseImporter.hh \
    OpenMesh/Core/IO/importer/ImporterT.hh \
    OpenMesh/Core/IO/reader/BaseReader.hh \
    OpenMesh/Core/IO/reader/OBJReader.hh \
    OpenMesh/Core/IO/reader/OFFReader.hh \
    OpenMesh/Core/IO/reader/OMReader.hh \
    OpenMesh/Core/IO/reader/PLYReader.hh \
    OpenMesh/Core/IO/reader/STLReader.hh \
    OpenMesh/Core/IO/writer/BaseWriter.hh \
    OpenMesh/Core/IO/writer/OBJWriter.hh \
    OpenMesh/Core/IO/writer/OFFWriter.hh \
    OpenMesh/Core/IO/writer/OMWriter.hh \
    OpenMesh/Core/IO/writer/PLYWriter.hh \
    OpenMesh/Core/IO/writer/STLWriter.hh \
    OpenMesh/Core/IO/writer/VTKWriter.hh \
    OpenMesh/Core/Mesh/ArrayItems.hh \
    OpenMesh/Core/Mesh/ArrayKernel.hh \
    OpenMesh/Core/Mesh/ArrayKernelT_impl.hh \
    OpenMesh/Core/Mesh/AttribKernelT.hh \
    OpenMesh/Core/Mesh/Attributes.hh \
    OpenMesh/Core/Mesh/BaseKernel.hh \
    OpenMesh/Core/Mesh/BaseMesh.hh \
    OpenMesh/Core/Mesh/Casts.hh \
    OpenMesh/Core/Mesh/CirculatorsT.hh \
    OpenMesh/Core/Mesh/DefaultPolyMesh.hh \
    OpenMesh/Core/Mesh/DefaultTriMesh.hh \
    OpenMesh/Core/Mesh/FinalMeshItemsT.hh \
    OpenMesh/Core/Mesh/Handles.hh \
    OpenMesh/Core/Mesh/IteratorsT.hh \
    OpenMesh/Core/Mesh/PolyConnectivity.hh \
    OpenMesh/Core/Mesh/PolyConnectivity_inline_impl.hh \
    OpenMesh/Core/Mesh/PolyMeshT.hh \
    OpenMesh/Core/Mesh/PolyMeshT_impl.hh \
    OpenMesh/Core/Mesh/PolyMesh_ArrayKernelT.hh \
    OpenMesh/Core/Mesh/SmartHandles.hh \
    OpenMesh/Core/Mesh/SmartRange.hh \
    OpenMesh/Core/Mesh/Status.hh \
    OpenMesh/Core/Mesh/Tags.hh \
    OpenMesh/Core/Mesh/Traits.hh \
    OpenMesh/Core/Mesh/TriConnectivity.hh \
    OpenMesh/Core/Mesh/TriMeshT.hh \
    OpenMesh/Core/Mesh/TriMeshT_impl.hh \
    OpenMesh/Core/Mesh/TriMesh_ArrayKernelT.hh \
    OpenMesh/Core/Mesh/gen/circulators_header.hh \
    OpenMesh/Core/Mesh/gen/circulators_template.hh \
    OpenMesh/Core/Mesh/gen/footer.hh \
    OpenMesh/Core/Mesh/gen/iterators_header.hh \
    OpenMesh/Core/Mesh/gen/iterators_template.hh \
    OpenMesh/Core/System/OpenMeshDLLMacros.hh \
    OpenMesh/Core/System/compiler.hh \
    OpenMesh/Core/System/config.h \
    OpenMesh/Core/System/config.hh \
    OpenMesh/Core/System/mostream.hh \
    OpenMesh/Core/System/omstream.hh \
    OpenMesh/Core/Templates/bla.hh \
    OpenMesh/Core/Templates/blaT_impl.hh \
    OpenMesh/Core/Utils/AutoPropertyHandleT.hh \
    OpenMesh/Core/Utils/BaseProperty.hh \
    OpenMesh/Core/Utils/Endian.hh \
    OpenMesh/Core/Utils/GenProg.hh \
    OpenMesh/Core/Utils/HandleToPropHandle.hh \
    OpenMesh/Core/Utils/Noncopyable.hh \
    OpenMesh/Core/Utils/Property.hh \
    OpenMesh/Core/Utils/PropertyContainer.hh \
    OpenMesh/Core/Utils/PropertyManager.hh \
    OpenMesh/Core/Utils/RandomNumberGenerator.hh \
    OpenMesh/Core/Utils/SingletonT.hh \
    OpenMesh/Core/Utils/SingletonT_impl.hh \
    OpenMesh/Core/Utils/color_cast.hh \
    OpenMesh/Core/Utils/typename.hh \
    OpenMesh/Core/Utils/vector_cast.hh \
    OpenMesh/Core/Utils/vector_traits.hh \
    OpenMesh/Tools/Decimater/BaseDecimaterT.hh \
    OpenMesh/Tools/Decimater/BaseDecimaterT_impl.hh \
    OpenMesh/Tools/Decimater/CollapseInfoT.hh \
    OpenMesh/Tools/Decimater/DecimaterT.hh \
    OpenMesh/Tools/Decimater/DecimaterT_impl.hh \
    OpenMesh/Tools/Decimater/McDecimaterT.hh \
    OpenMesh/Tools/Decimater/McDecimaterT_impl.hh \
    OpenMesh/Tools/Decimater/MixedDecimaterT.hh \
    OpenMesh/Tools/Decimater/MixedDecimaterT_impl.hh \
    OpenMesh/Tools/Decimater/ModAspectRatioT.hh \
    OpenMesh/Tools/Decimater/ModAspectRatioT_impl.hh \
    OpenMesh/Tools/Decimater/ModBaseT.hh \
    OpenMesh/Tools/Decimater/ModEdgeLengthT.hh \
    OpenMesh/Tools/Decimater/ModEdgeLengthT_impl.hh \
    OpenMesh/Tools/Decimater/ModHausdorffT.hh \
    OpenMesh/Tools/Decimater/ModHausdorffT_impl.hh \
    OpenMesh/Tools/Decimater/ModIndependentSetsT.hh \
    OpenMesh/Tools/Decimater/ModNormalDeviationT.hh \
    OpenMesh/Tools/Decimater/ModNormalFlippingT.hh \
    OpenMesh/Tools/Decimater/ModProgMeshT.hh \
    OpenMesh/Tools/Decimater/ModProgMeshT_impl.hh \
    OpenMesh/Tools/Decimater/ModQuadricT.hh \
    OpenMesh/Tools/Decimater/ModQuadricT_impl.hh \
    OpenMesh/Tools/Decimater/ModRoundnessT.hh \
    OpenMesh/Tools/Decimater/Observer.hh \
    OpenMesh/Tools/Dualizer/meshDualT.hh \
    OpenMesh/Tools/Kernel_OSG/ArrayKernelT.hh \
    OpenMesh/Tools/Kernel_OSG/AttribKernelT.hh \
    OpenMesh/Tools/Kernel_OSG/PropertyKernel.hh \
    OpenMesh/Tools/Kernel_OSG/PropertyT.hh \
    OpenMesh/Tools/Kernel_OSG/Traits.hh \
    OpenMesh/Tools/Kernel_OSG/TriMesh_OSGArrayKernelT.hh \
    OpenMesh/Tools/Kernel_OSG/VectorAdapter.hh \
    OpenMesh/Tools/Kernel_OSG/bindT.hh \
    OpenMesh/Tools/Kernel_OSG/color_cast.hh \
    OpenMesh/Tools/SmartTagger/SmartTaggerT.hh \
    OpenMesh/Tools/SmartTagger/SmartTaggerT_impl.hh \
    OpenMesh/Tools/Smoother/JacobiLaplaceSmootherT.hh \
    OpenMesh/Tools/Smoother/JacobiLaplaceSmootherT_impl.hh \
    OpenMesh/Tools/Smoother/LaplaceSmootherT.hh \
    OpenMesh/Tools/Smoother/LaplaceSmootherT_impl.hh \
    OpenMesh/Tools/Smoother/SmootherT.hh \
    OpenMesh/Tools/Smoother/SmootherT_impl.hh \
    OpenMesh/Tools/Smoother/smooth_mesh.hh \
    OpenMesh/Tools/Subdivider/Adaptive/Composite/CompositeT.hh \
    OpenMesh/Tools/Subdivider/Adaptive/Composite/CompositeT_impl.hh \
    OpenMesh/Tools/Subdivider/Adaptive/Composite/CompositeTraits.hh \
    OpenMesh/Tools/Subdivider/Adaptive/Composite/RuleInterfaceT.hh \
    OpenMesh/Tools/Subdivider/Adaptive/Composite/RulesT.hh \
    OpenMesh/Tools/Subdivider/Adaptive/Composite/RulesT_impl.hh \
    OpenMesh/Tools/Subdivider/Adaptive/Composite/Traits.hh \
    OpenMesh/Tools/Subdivider/Uniform/CatmullClarkT.hh \
    OpenMesh/Tools/Subdivider/Uniform/CatmullClarkT_impl.hh \
    OpenMesh/Tools/Subdivider/Uniform/Composite/CompositeT.hh \
    OpenMesh/Tools/Subdivider/Uniform/Composite/CompositeT_impl.hh \
    OpenMesh/Tools/Subdivider/Uniform/Composite/CompositeTraits.hh \
    OpenMesh/Tools/Subdivider/Uniform/CompositeLoopT.hh \
    OpenMesh/Tools/Subdivider/Uniform/CompositeSqrt3T.hh \
    OpenMesh/Tools/Subdivider/Uniform/LongestEdgeT.hh \
    OpenMesh/Tools/Subdivider/Uniform/LoopT.hh \
    OpenMesh/Tools/Subdivider/Uniform/MidpointT.hh \
    OpenMesh/Tools/Subdivider/Uniform/ModifiedButterFlyT.hh \
    OpenMesh/Tools/Subdivider/Uniform/Sqrt3InterpolatingSubdividerLabsikGreinerT.hh \
    OpenMesh/Tools/Subdivider/Uniform/Sqrt3T.hh \
    OpenMesh/Tools/Subdivider/Uniform/SubdividerT.hh \
    OpenMesh/Tools/Utils/Config.hh \
    OpenMesh/Tools/Utils/GLConstAsString.hh \
    OpenMesh/Tools/Utils/Gnuplot.hh \
    OpenMesh/Tools/Utils/HeapT.hh \
    OpenMesh/Tools/Utils/MeshCheckerT.hh \
    OpenMesh/Tools/Utils/MeshCheckerT_impl.hh \
    OpenMesh/Tools/Utils/NumLimitsT.hh \
    OpenMesh/Tools/Utils/StripifierT.hh \
    OpenMesh/Tools/Utils/StripifierT_impl.hh \
    OpenMesh/Tools/Utils/TestingFramework.hh \
    OpenMesh/Tools/Utils/Timer.hh \
    OpenMesh/Tools/Utils/conio.hh \
    OpenMesh/Tools/Utils/getopt.h \
    OpenMesh/Tools/VDPM/MeshTraits.hh \
    OpenMesh/Tools/VDPM/StreamingDef.hh \
    OpenMesh/Tools/VDPM/VFront.hh \
    OpenMesh/Tools/VDPM/VHierarchy.hh \
    OpenMesh/Tools/VDPM/VHierarchyNode.hh \
    OpenMesh/Tools/VDPM/VHierarchyNodeIndex.hh \
    OpenMesh/Tools/VDPM/VHierarchyWindow.hh \
    OpenMesh/Tools/VDPM/ViewingParameters.hh \
    mainwindow.h \
    surfrec_io/code/io.h \
    surfrec_io/extern/Eigen/Eigen/Cholesky \
    surfrec_io/extern/Eigen/Eigen/CholmodSupport \
    surfrec_io/extern/Eigen/Eigen/Core \
    surfrec_io/extern/Eigen/Eigen/Dense \
    surfrec_io/extern/Eigen/Eigen/Eigen \
    surfrec_io/extern/Eigen/Eigen/Eigenvalues \
    surfrec_io/extern/Eigen/Eigen/Geometry \
    surfrec_io/extern/Eigen/Eigen/Householder \
    surfrec_io/extern/Eigen/Eigen/IterativeLinearSolvers \
    surfrec_io/extern/Eigen/Eigen/Jacobi \
    surfrec_io/extern/Eigen/Eigen/KLUSupport \
    surfrec_io/extern/Eigen/Eigen/LU \
    surfrec_io/extern/Eigen/Eigen/MetisSupport \
    surfrec_io/extern/Eigen/Eigen/OrderingMethods \
    surfrec_io/extern/Eigen/Eigen/PaStiXSupport \
    surfrec_io/extern/Eigen/Eigen/PardisoSupport \
    surfrec_io/extern/Eigen/Eigen/QR \
    surfrec_io/extern/Eigen/Eigen/QtAlignedMalloc \
    surfrec_io/extern/Eigen/Eigen/SPQRSupport \
    surfrec_io/extern/Eigen/Eigen/SVD \
    surfrec_io/extern/Eigen/Eigen/Sparse \
    surfrec_io/extern/Eigen/Eigen/SparseCholesky \
    surfrec_io/extern/Eigen/Eigen/SparseCore \
    surfrec_io/extern/Eigen/Eigen/SparseLU \
    surfrec_io/extern/Eigen/Eigen/SparseQR \
    surfrec_io/extern/Eigen/Eigen/StdDeque \
    surfrec_io/extern/Eigen/Eigen/StdList \
    surfrec_io/extern/Eigen/Eigen/StdVector \
    surfrec_io/extern/Eigen/Eigen/SuperLUSupport \
    surfrec_io/extern/Eigen/Eigen/UmfPackSupport \
    surfrec_io/extern/Eigen/Eigen/src/Cholesky/LDLT.h \
    surfrec_io/extern/Eigen/Eigen/src/Cholesky/LLT.h \
    surfrec_io/extern/Eigen/Eigen/src/Cholesky/LLT_LAPACKE.h \
    surfrec_io/extern/Eigen/Eigen/src/CholmodSupport/CholmodSupport.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/ArithmeticSequence.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Array.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/ArrayBase.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/ArrayWrapper.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Assign.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/AssignEvaluator.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Assign_MKL.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/BandMatrix.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Block.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/BooleanRedux.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/CommaInitializer.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/ConditionEstimator.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/CoreEvaluators.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/CoreIterators.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/CwiseBinaryOp.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/CwiseNullaryOp.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/CwiseTernaryOp.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/CwiseUnaryOp.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/CwiseUnaryView.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/DenseBase.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/DenseCoeffsBase.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/DenseStorage.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Diagonal.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/DiagonalMatrix.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/DiagonalProduct.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Dot.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/EigenBase.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/ForceAlignedAccess.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Fuzzy.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/GeneralProduct.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/GenericPacketMath.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/GlobalFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/IO.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/IndexedView.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Inverse.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Map.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/MapBase.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/MathFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/MathFunctionsImpl.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Matrix.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/MatrixBase.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/NestByValue.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/NoAlias.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/NumTraits.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/PartialReduxEvaluator.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/PermutationMatrix.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/PlainObjectBase.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Product.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/ProductEvaluators.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Random.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Redux.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Ref.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Replicate.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Reshaped.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/ReturnByValue.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Reverse.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Select.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/SelfAdjointView.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/SelfCwiseBinaryOp.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Solve.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/SolveTriangular.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/SolverBase.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/StableNorm.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/StlIterators.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Stride.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Swap.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Transpose.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Transpositions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/TriangularMatrix.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/VectorBlock.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/VectorwiseOp.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/Visitor.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/AVX/Complex.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/AVX/MathFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/AVX/PacketMath.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/AVX/TypeCasting.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/AVX512/Complex.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/AVX512/MathFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/AVX512/PacketMath.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/AVX512/TypeCasting.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/AltiVec/Complex.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/AltiVec/PacketMath.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/CUDA/Complex.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/Default/ConjHelper.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/Default/GenericPacketMathFunctionsFwd.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/Default/Half.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/Default/Settings.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/Default/TypeCasting.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/GPU/MathFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/GPU/PacketMath.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/GPU/TypeCasting.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/HIP/hcc/math_constants.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/MSA/Complex.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/MSA/MathFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/MSA/PacketMath.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/NEON/Complex.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/NEON/MathFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/NEON/PacketMath.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/NEON/TypeCasting.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/SSE/Complex.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/SSE/MathFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/SSE/PacketMath.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/SSE/TypeCasting.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/SYCL/InteropHeaders.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/SYCL/MathFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/SYCL/PacketMath.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/SYCL/SyclMemoryModel.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/SYCL/TypeCasting.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/ZVector/Complex.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/ZVector/MathFunctions.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/arch/ZVector/PacketMath.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/functors/AssignmentFunctors.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/functors/BinaryFunctors.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/functors/NullaryFunctors.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/functors/StlFunctors.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/functors/TernaryFunctors.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/functors/UnaryFunctors.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/GeneralMatrixMatrix.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/GeneralMatrixVector.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/Parallelizer.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/SelfadjointMatrixVector.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/SelfadjointProduct.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/SelfadjointRank2Update.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/TriangularMatrixMatrix.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/TriangularMatrixVector.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/TriangularSolverMatrix.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/products/TriangularSolverVector.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/BlasUtil.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/ConfigureVectorization.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/Constants.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/DisableStupidWarnings.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/ForwardDeclarations.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/IndexedViewHelper.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/IntegralConstant.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/MKL_support.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/Macros.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/Memory.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/Meta.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/NonMPL2.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/ReenableStupidWarnings.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/ReshapedHelper.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/StaticAssert.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/SymbolicIndex.h \
    surfrec_io/extern/Eigen/Eigen/src/Core/util/XprHelper.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/ComplexSchur.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/EigenSolver.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/RealQZ.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/RealSchur.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
    surfrec_io/extern/Eigen/Eigen/src/Eigenvalues/Tridiagonalization.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/AlignedBox.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/AngleAxis.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/EulerAngles.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/Homogeneous.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/Hyperplane.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/OrthoMethods.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/ParametrizedLine.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/Quaternion.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/Rotation2D.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/RotationBase.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/Scaling.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/Transform.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/Translation.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/Umeyama.h \
    surfrec_io/extern/Eigen/Eigen/src/Geometry/arch/Geometry_SSE.h \
    surfrec_io/extern/Eigen/Eigen/src/Householder/BlockHouseholder.h \
    surfrec_io/extern/Eigen/Eigen/src/Householder/Householder.h \
    surfrec_io/extern/Eigen/Eigen/src/Householder/HouseholderSequence.h \
    surfrec_io/extern/Eigen/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
    surfrec_io/extern/Eigen/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
    surfrec_io/extern/Eigen/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
    surfrec_io/extern/Eigen/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
    surfrec_io/extern/Eigen/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
    surfrec_io/extern/Eigen/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
    surfrec_io/extern/Eigen/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
    surfrec_io/extern/Eigen/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
    surfrec_io/extern/Eigen/Eigen/src/Jacobi/Jacobi.h \
    surfrec_io/extern/Eigen/Eigen/src/KLUSupport/KLUSupport.h \
    surfrec_io/extern/Eigen/Eigen/src/LU/Determinant.h \
    surfrec_io/extern/Eigen/Eigen/src/LU/FullPivLU.h \
    surfrec_io/extern/Eigen/Eigen/src/LU/InverseImpl.h \
    surfrec_io/extern/Eigen/Eigen/src/LU/PartialPivLU.h \
    surfrec_io/extern/Eigen/Eigen/src/LU/PartialPivLU_LAPACKE.h \
    surfrec_io/extern/Eigen/Eigen/src/LU/arch/Inverse_SSE.h \
    surfrec_io/extern/Eigen/Eigen/src/MetisSupport/MetisSupport.h \
    surfrec_io/extern/Eigen/Eigen/src/OrderingMethods/Amd.h \
    surfrec_io/extern/Eigen/Eigen/src/OrderingMethods/Eigen_Colamd.h \
    surfrec_io/extern/Eigen/Eigen/src/OrderingMethods/Ordering.h \
    surfrec_io/extern/Eigen/Eigen/src/PaStiXSupport/PaStiXSupport.h \
    surfrec_io/extern/Eigen/Eigen/src/PardisoSupport/PardisoSupport.h \
    surfrec_io/extern/Eigen/Eigen/src/QR/ColPivHouseholderQR.h \
    surfrec_io/extern/Eigen/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
    surfrec_io/extern/Eigen/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
    surfrec_io/extern/Eigen/Eigen/src/QR/FullPivHouseholderQR.h \
    surfrec_io/extern/Eigen/Eigen/src/QR/HouseholderQR.h \
    surfrec_io/extern/Eigen/Eigen/src/QR/HouseholderQR_LAPACKE.h \
    surfrec_io/extern/Eigen/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
    surfrec_io/extern/Eigen/Eigen/src/SVD/BDCSVD.h \
    surfrec_io/extern/Eigen/Eigen/src/SVD/JacobiSVD.h \
    surfrec_io/extern/Eigen/Eigen/src/SVD/JacobiSVD_LAPACKE.h \
    surfrec_io/extern/Eigen/Eigen/src/SVD/SVDBase.h \
    surfrec_io/extern/Eigen/Eigen/src/SVD/UpperBidiagonalization.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCholesky/SimplicialCholesky.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/AmbiVector.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/CompressedStorage.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/MappedSparseMatrix.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseAssign.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseBlock.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseColEtree.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseCompressedBase.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseDenseProduct.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseDiagonalProduct.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseDot.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseFuzzy.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseMap.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseMatrix.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseMatrixBase.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparsePermutation.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseProduct.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseRedux.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseRef.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseSelfAdjointView.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseSolverBase.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseTranspose.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseTriangularView.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseUtil.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseVector.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/SparseView.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseCore/TriangularSolver.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLUImpl.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_Memory.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_Structs.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_Utils.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_column_bmod.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_column_dfs.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_panel_bmod.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_panel_dfs.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_pivotL.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_pruneL.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseLU/SparseLU_relax_snode.h \
    surfrec_io/extern/Eigen/Eigen/src/SparseQR/SparseQR.h \
    surfrec_io/extern/Eigen/Eigen/src/StlSupport/StdDeque.h \
    surfrec_io/extern/Eigen/Eigen/src/StlSupport/StdList.h \
    surfrec_io/extern/Eigen/Eigen/src/StlSupport/StdVector.h \
    surfrec_io/extern/Eigen/Eigen/src/StlSupport/details.h \
    surfrec_io/extern/Eigen/Eigen/src/SuperLUSupport/SuperLUSupport.h \
    surfrec_io/extern/Eigen/Eigen/src/UmfPackSupport/UmfPackSupport.h \
    surfrec_io/extern/Eigen/Eigen/src/misc/Image.h \
    surfrec_io/extern/Eigen/Eigen/src/misc/Kernel.h \
    surfrec_io/extern/Eigen/Eigen/src/misc/RealSvd2x2.h \
    surfrec_io/extern/Eigen/Eigen/src/misc/blas.h \
    surfrec_io/extern/Eigen/Eigen/src/misc/lapack.h \
    surfrec_io/extern/Eigen/Eigen/src/misc/lapacke.h \
    surfrec_io/extern/Eigen/Eigen/src/misc/lapacke_mangling.h \
    surfrec_io/extern/Eigen/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
    surfrec_io/extern/Eigen/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
    surfrec_io/extern/Eigen/Eigen/src/plugins/BlockMethods.h \
    surfrec_io/extern/Eigen/Eigen/src/plugins/CommonCwiseBinaryOps.h \
    surfrec_io/extern/Eigen/Eigen/src/plugins/CommonCwiseUnaryOps.h \
    surfrec_io/extern/Eigen/Eigen/src/plugins/IndexedViewMethods.h \
    surfrec_io/extern/Eigen/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
    surfrec_io/extern/Eigen/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
    surfrec_io/extern/Eigen/Eigen/src/plugins/ReshapedMethods.h \
    surfrec_io/extern/happly.h \
    surfrec_io/extern/partio/src/lib/Partio.h \
    surfrec_io/extern/partio/src/lib/PartioAttribute.h \
    surfrec_io/extern/partio/src/lib/PartioConfig.h \
    surfrec_io/extern/partio/src/lib/PartioIterator.h \
    surfrec_io/extern/partio/src/lib/PartioVec3.h \
    surfrec_io/extern/partio/src/lib/core/KdTree.h \
    surfrec_io/extern/partio/src/lib/core/Mutex.h \
    surfrec_io/extern/partio/src/lib/core/ParticleCaching.h \
    surfrec_io/extern/partio/src/lib/core/ParticleHeaders.h \
    surfrec_io/extern/partio/src/lib/core/ParticleSimple.h \
    surfrec_io/extern/partio/src/lib/core/ParticleSimpleInterleave.h \
    surfrec_io/extern/partio/src/lib/io/PartioEndian.h \
    surfrec_io/extern/partio/src/lib/io/ZIP.h \
    surfrec_io/extern/partio/src/lib/io/half2float.h \
    surfrec_io/extern/partio/src/lib/io/pdb.h \
    surfrec_io/extern/partio/src/lib/io/readers.h \
    surfrec_io/extern/vtkio/ByteBuffer.h \
    surfrec_io/extern/vtkio/VTKStream.h \
    surfrec_io/extern/vtkio/dynamic_types.h \
    surfrec_io/extern/vtkio/endianness.h \
    surfrec_io/extern/vtkio/stream_io.h \
    surfrec_io/extern/vtkio/tables.h \
    surfrec_io/extern/zlib/src/crc32.h \
    surfrec_io/extern/zlib/src/deflate.h \
    surfrec_io/extern/zlib/src/inffast.h \
    surfrec_io/extern/zlib/src/inffixed.h \
    surfrec_io/extern/zlib/src/inflate.h \
    surfrec_io/extern/zlib/src/inftrees.h \
    surfrec_io/extern/zlib/src/trees.h \
    surfrec_io/extern/zlib/src/zconf.h \
    surfrec_io/extern/zlib/src/zlib.h \
    surfrec_io/extern/zlib/src/zutil.h

FORMS += \
    mainwindow.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target


RESOURCES += \
    resources.qrc

DISTFILES += \
    SurfaceReconstruction/alg/edgeIdentification.data \
    SurfaceReconstruction/alg/possibleGeometry.data \
    SurfaceReconstruction/doc/Doxyfile \
    CompactNSearch/.github/workflows/build-linux.yml \
    CompactNSearch/.github/workflows/build-windows.yml \
    CompactNSearch/CMakeLists.txt \
    CompactNSearch/LICENSE \
    CompactNSearch/README.md \
    CompactNSearch/demo/CMakeLists.txt \
    CompactNSearch/extern/libmorton/LICENSE \
    CompactNSearch/extern/libmorton/README.md \
    OpenMesh/Core/CMakeLists.txt \
    OpenMesh/Core/Mesh/gen/generate.sh \
    OpenMesh/Lib/OpenMeshCore.lib \
    OpenMesh/Lib/OpenMeshTools.lib \
    OpenMesh/Tools/CMakeLists.txt \
    OpenMesh/Tools/VDPM/xpm/fileopen.xpm \
    OpenMesh/Tools/VDPM/xpm/fileprint.xpm \
    OpenMesh/Tools/VDPM/xpm/filesave.xpm \
    surfrec_io/extern/Eigen/CMakeLists.txt \
    surfrec_io/extern/Eigen/signature_of_eigen3_matrix_library \
    surfrec_io/extern/partio/CMakeLists.txt \
    surfrec_io/extern/partio/README \
    surfrec_io/extern/partio/src/lib/CMakeLists.txt \
    surfrec_io/extern/zlib/CMakeLists.txt


INCLUDEPATH += $$PWD/SurfaceReconstruction/data
INCLUDEPATH += $$PWD/SurfaceReconstruction/in
INCLUDEPATH += $$PWD/SurfaceReconstruction/out
INCLUDEPATH += $$PWD/SurfaceReconstruction/alg/kernel
INCLUDEPATH += $$PWD/SurfaceReconstruction/alg/level
INCLUDEPATH += $$PWD/SurfaceReconstruction/alg/nsearch
INCLUDEPATH += $$PWD/SurfaceReconstruction/alg/post
INCLUDEPATH += $$PWD/surfrec_io/extern/partio/src/lib
INCLUDEPATH += $$PWD/surfrec_io/extern/vtkio
INCLUDEPATH += $$PWD/CompactNSearch/include
INCLUDEPATH += $$PWD/surfrec_io/extern/
